version: '3'
services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: webflux
      MYSQL_USER: user
      MYSQL_PASSWORD: 10041004
      MYSQL_ROOT_PASSWORD: 10041004
    volumes:
      - 'mysqldata:/var/lib/mysql'
volumes:
  mysqldata: